export const formFields = [
    {
        fieldName:'Name',
        type:'text',
        required:true,
        min:null,
        maxLength:15,
        value:""
    },
    {
        fieldName:'Age',
        type:'number',
        required:true,
        min:18,
        maxLength:null,
        value:""
    },
    {
        fieldName:'Gender',
        type:'radio',
        required:true,
        min:null,
        maxLength:null,
        value:"Male"
    },
    {
        fieldName:'Gender',
        type:'radio',
        required:true,
        min:null,
        maxLength:null,
        value:"Female"
    },
    {
        fieldName:'Gender',
        type:'radio',
        required:true,
        min:null,
        maxLength:null,
        value:"Other"
    },
    {
        fieldName:'Hobbies',
        type:'checkbox',
        required:false,
        min:null,
        maxLength:null,
        value:"Listening Music"
    },
    {
        fieldName:'Hobbies',
        type:'checkbox',
        required:false,
        min:null,
        maxLength:null,
        value:"Singing"
    }
]